-- MySQL Script generated by MySQL Workbench
-- 09/21/16 21:49:33
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema laPecosa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema laPecosa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `laPecosa` DEFAULT CHARACTER SET utf8 ;
USE `laPecosa` ;

-- -----------------------------------------------------
-- Table `laPecosa`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`persona` (
  `idPersona` INT NOT NULL AUTO_INCREMENT,
  `documento` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(35) NOT NULL,
  `fechaNac` DATE NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `nacionalidad` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laPecosa`.`planillaero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`planillaero` (
  `codPlanillero` INT NOT NULL AUTO_INCREMENT,
  `idPlanillero` INT NOT NULL,
  `idPerosna` INT NOT NULL,
  `persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idPlanillero`, `persona_idPersona`),
  CONSTRAINT `fk_planillaero_persona`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `laPecosa`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_planillaero_persona_idx` ON `laPecosa`.`planillaero` (`persona_idPersona` ASC);


-- -----------------------------------------------------
-- Table `laPecosa`.`jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`jugador` (
  `codJugador` INT NOT NULL AUTO_INCREMENT,
  `idJugador` INT NOT NULL,
  `idEquipo` VARCHAR(15) NOT NULL,
  `numJugador` VARCHAR(3) NOT NULL,
  `persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idJugador`, `persona_idPersona`),
  CONSTRAINT `fk_jugador_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `laPecosa`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_jugador_persona1_idx` ON `laPecosa`.`jugador` (`persona_idPersona` ASC);


-- -----------------------------------------------------
-- Table `laPecosa`.`cancha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`cancha` (
  `codCancha` INT NOT NULL AUTO_INCREMENT,
  `idCancha` VARCHAR(45) NOT NULL,
  `direcCancha` VARCHAR(45) NOT NULL,
  `nombreSede` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`idCancha`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laPecosa`.`encuentroPartido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`encuentroPartido` (
  `codEncuentroPartido` INT NOT NULL AUTO_INCREMENT,
  `idEncuentroPartido` INT NOT NULL,
  `fechaPartido` VARCHAR(20) NOT NULL,
  `horaPartido` VARCHAR(20) NOT NULL,
  `jugador_idJugador` INT NOT NULL,
  `jugador_persona_idPersona` INT NOT NULL,
  `cancha_idCancha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEncuentroPartido`, `jugador_idJugador`, `jugador_persona_idPersona`, `cancha_idCancha`),
  CONSTRAINT `fk_encuentroPartido_jugador1`
    FOREIGN KEY (`jugador_idJugador` , `jugador_persona_idPersona`)
    REFERENCES `laPecosa`.`jugador` (`idJugador` , `persona_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encuentroPartido_cancha1`
    FOREIGN KEY (`cancha_idCancha`)
    REFERENCES `laPecosa`.`cancha` (`idCancha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_encuentroPartido_jugador1_idx` ON `laPecosa`.`encuentroPartido` (`jugador_idJugador` ASC, `jugador_persona_idPersona` ASC);

CREATE INDEX `fk_encuentroPartido_cancha1_idx` ON `laPecosa`.`encuentroPartido` (`cancha_idCancha` ASC);


-- -----------------------------------------------------
-- Table `laPecosa`.`torneo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`torneo` (
  `codTorneo` INT NOT NULL AUTO_INCREMENT,
  `idtorneo` VARCHAR(35) NOT NULL,
  `cancha` VARCHAR(35) NOT NULL,
  `nombreTorneo` VARCHAR(30) NOT NULL,
  `cancha_idCancha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtorneo`, `cancha_idCancha`),
  CONSTRAINT `fk_torneo_cancha1`
    FOREIGN KEY (`cancha_idCancha`)
    REFERENCES `laPecosa`.`cancha` (`idCancha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_torneo_cancha1_idx` ON `laPecosa`.`torneo` (`cancha_idCancha` ASC);


-- -----------------------------------------------------
-- Table `laPecosa`.`equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`equipo` (
  `codEquipo` INT NOT NULL AUTO_INCREMENT,
  `idequipo` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(35) NOT NULL,
  `equipo` VARCHAR(4525) NOT NULL,
  `torneo_idtorneo` VARCHAR(35) NOT NULL,
  `torneo_cancha_idCancha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idequipo`, `torneo_idtorneo`, `torneo_cancha_idCancha`),
  CONSTRAINT `fk_equipo_torneo1`
    FOREIGN KEY (`torneo_idtorneo` , `torneo_cancha_idCancha`)
    REFERENCES `laPecosa`.`torneo` (`idtorneo` , `cancha_idCancha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_equipo_torneo1_idx` ON `laPecosa`.`equipo` (`torneo_idtorneo` ASC, `torneo_cancha_idCancha` ASC);


-- -----------------------------------------------------
-- Table `laPecosa`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`usuario` (
  `codUsuario` INT NOT NULL AUTO_INCREMENT,
  `idregistro` VARCHAR(15) NOT NULL,
  `numJugador` VARCHAR(3) NOT NULL,
  `persona_idPersona` INT NOT NULL,
  `equipo_idequipo` VARCHAR(20) NOT NULL,
  `equipo_torneo_idtorneo` VARCHAR(35) NOT NULL,
  `equipo_torneo_cancha_idCancha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idregistro`, `persona_idPersona`, `equipo_idequipo`, `equipo_torneo_idtorneo`, `equipo_torneo_cancha_idCancha`),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `laPecosa`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_equipo1`
    FOREIGN KEY (`equipo_idequipo` , `equipo_torneo_idtorneo` , `equipo_torneo_cancha_idCancha`)
    REFERENCES `laPecosa`.`equipo` (`idequipo` , `torneo_idtorneo` , `torneo_cancha_idCancha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_usuario_persona1_idx` ON `laPecosa`.`usuario` (`persona_idPersona` ASC);

CREATE INDEX `fk_usuario_equipo1_idx` ON `laPecosa`.`usuario` (`equipo_idequipo` ASC, `equipo_torneo_idtorneo` ASC, `equipo_torneo_cancha_idCancha` ASC);


-- -----------------------------------------------------
-- Table `laPecosa`.`arbitro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`arbitro` (
  `codArbitro` INT NOT NULL AUTO_INCREMENT,
  `idPersona` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` DATETIME NOT NULL,
  `idArbitro` VARCHAR(45) NOT NULL,
  `persona_idPersona` INT NOT NULL,
  PRIMARY KEY (`idPersona`, `persona_idPersona`),
  CONSTRAINT `fk_arbitro_persona1`
    FOREIGN KEY (`persona_idPersona`)
    REFERENCES `laPecosa`.`persona` (`idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_arbitro_persona1_idx` ON `laPecosa`.`arbitro` (`persona_idPersona` ASC);


-- -----------------------------------------------------
-- Table `laPecosa`.`tablaRegistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`tablaRegistro` (
  `idTablaRegistro` VARCHAR(25) NOT NULL,
  `tabProximaFecha` VARCHAR(45) NOT NULL,
  `tabPocisiones` VARCHAR(45) NOT NULL,
  `tabSancionados` VARCHAR(45) NOT NULL,
  `tabGoleadores` VARCHAR(45) NOT NULL,
  `tabGrupos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTablaRegistro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `laPecosa`.`planillaero_has_tablaRegistro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `laPecosa`.`planillaero_has_tablaRegistro` (
  `planillaero_idPlanillero` INT NOT NULL,
  `planillaero_persona_idPersona` INT NOT NULL,
  `tablaRegistro_idTablaRegistro` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`planillaero_idPlanillero`, `planillaero_persona_idPersona`, `tablaRegistro_idTablaRegistro`),
  CONSTRAINT `fk_planillaero_has_tablaRegistro_planillaero1`
    FOREIGN KEY (`planillaero_idPlanillero` , `planillaero_persona_idPersona`)
    REFERENCES `laPecosa`.`planillaero` (`idPlanillero` , `persona_idPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_planillaero_has_tablaRegistro_tablaRegistro1`
    FOREIGN KEY (`tablaRegistro_idTablaRegistro`)
    REFERENCES `laPecosa`.`tablaRegistro` (`idTablaRegistro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_planillaero_has_tablaRegistro_tablaRegistro1_idx` ON `laPecosa`.`planillaero_has_tablaRegistro` (`tablaRegistro_idTablaRegistro` ASC);

CREATE INDEX `fk_planillaero_has_tablaRegistro_planillaero1_idx` ON `laPecosa`.`planillaero_has_tablaRegistro` (`planillaero_idPlanillero` ASC, `planillaero_persona_idPersona` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
